create database polleriacaribe;
use polleriacaribe;
drop database polleriacaribe;

CREATE TABLE CLIENTE (
    CODCLI int auto_increment,
    DNICLI char(8) NOT NULL,
    NOMCLI varchar(50) NOT NULL,
    APECLI varchar(50) NOT NULL,
    CELCLI char(9) NOT NULL,
    GMLCLI varchar(50) NOT NULL,
    UBIGEO_CODUBIG char(9) NOT NULL,
    CONSTRAINT CLIENTE_pk PRIMARY KEY (CODCLI)
);

-- Table: EMPLEADO
CREATE TABLE EMPLEADO (
    CODEMP int auto_increment,
    DNIEMP char(8) NOT NULL,
    NOMEMP varchar(50) NOT NULL,
    APEEMP varchar(50) NOT NULL,
    CELEMP char(9) NOT NULL,
    GMLEMP varchar(50) NOT NULL,
    CODUBIG char(9) NOT NULL,
    USEEMP varchar(200) NOT NULL,
    CONSTRAINT EMPLEADO_pk PRIMARY KEY (CODEMP)
);

-- Table: PEDIDO
CREATE TABLE PEDIDO (
    IDPED int auto_increment,
    USERPED varchar(500) NOT NULL,
    CELUSPED char(9) NOT NULL,
    EMAUSPED varchar(50) NOT NULL,
    FOODPED varchar(80) NOT NULL,
    MSGPED varchar(250) NOT NULL,
    CLIENTE_CODCLI int NOT NULL,
    CONSTRAINT PEDIDO_pk PRIMARY KEY (IDPED)
);

-- Table: PRODUCTO
CREATE TABLE PRODUCTO (
    CODPRO char(9) NOT NULL,
    NOMPRO varchar(50) NOT NULL,
    CATPRO char(1) NOT NULL,
    DESPRO varchar(500) NOT NULL,
    PREPRO decimal(8,2) NOT NULL,
    VENTA_IDVENT int NOT NULL,
    CLIENTE_CODCLI int NOT NULL,
    CONSTRAINT PRODUCTO_pk PRIMARY KEY (CODPRO)
);

-- Table: UBIGEO
CREATE TABLE UBIGEO (
    CODUBIG int auto_increment,
    PROUBI varchar(50) NOT NULL,
    DEPUBI varchar(50) NOT NULL,
    DISUBI varchar(50) NOT NULL,
    CONSTRAINT UBIGEO_pk PRIMARY KEY (CODUBIG)
);

-- Table: VENTA
CREATE TABLE VENTA (
    IDVENT int auto_increment,
    FECVENT date NOT NULL,
    TOTVENT double(5,2) NOT NULL,
    TIPVENT char(1) NOT NULL COMMENT 'E = Efectivo, Y = Yape, P = Plin, T = Transferencias',
    EMPLEADO_CODEMP int NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY (IDVENT)
);

-- Table: VENTA_DETALLE
CREATE TABLE VENTA_DETALLE (
    IDVENTDET int NOT NULL,
    CANVENTDET int NOT NULL,
    VENTA_IDVENT int NOT NULL,
    CONSTRAINT VENTA_DETALLE_pk PRIMARY KEY (IDVENTDET)
);

-- foreign keys
-- Reference: CLIENTE_UBIGEO (table: CLIENTE)
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_UBIGEO FOREIGN KEY CLIENTE_UBIGEO (UBIGEO_CODUBIG)
    REFERENCES UBIGEO (CODUBIG);

-- Reference: EMPLEADO_UBIGEO (table: EMPLEADO)
ALTER TABLE EMPLEADO ADD CONSTRAINT EMPLEADO_UBIGEO FOREIGN KEY EMPLEADO_UBIGEO (CODUBIG)
    REFERENCES UBIGEO (CODUBIG);

-- Reference: PEDIDO_CLIENTE (table: PEDIDO)
ALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_CLIENTE FOREIGN KEY PEDIDO_CLIENTE (CLIENTE_CODCLI)
    REFERENCES CLIENTE (CODCLI);

-- Reference: PRODUCTO_CLIENTE (table: PRODUCTO)
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_CLIENTE FOREIGN KEY PRODUCTO_CLIENTE (CLIENTE_CODCLI)
    REFERENCES PEDIDO (IDPED);

-- Reference: PRODUCTO_VENTA (table: PRODUCTO)
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_VENTA FOREIGN KEY PRODUCTO_VENTA (VENTA_IDVENT)
    REFERENCES VENTA (IDVENT);

-- Reference: VENTA_DETALLE_VENTA (table: VENTA_DETALLE)
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_VENTA FOREIGN KEY VENTA_DETALLE_VENTA (VENTA_IDVENT)
    REFERENCES VENTA (IDVENT);

-- Reference: VENTA_EMPLEADO (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_EMPLEADO FOREIGN KEY VENTA_EMPLEADO (EMPLEADO_CODEMP)
    REFERENCES EMPLEADO (CODEMP);


/* Insertar registros */
INSERT INTO PEDIDO
(USERPED, EMAUSPED, CELUSPED, FOODPED, MSGPED)
VALUES
('José Ramírez', 'jose.ramirez@outlook.com', '974815236', 'Arroz con Pollo', 'Por favor enviar a la dirección Av. Miraflores 253, San Vicente de Cañete'),
('Ana Guerra Solano', 'ana.guerra@gmail.com', '981526321', 'Sopa Seca de Gallina', 'Necesito 4 platos');

SELECT * FROM PEDIDO;

